D06/ex00/LifeProTips/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'sign_up' => 'users#new', as: 'sign_up'
  get 'log_in' => 'sessions#new', as: 'log_in'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

end

D06/ex00/LifeProTips/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :email, presence: true, uniqueness: true
	validates :password_digest, presence: true, length: {minimum: 8}
	validates_confirmation_of :password_digest
	
	def self.authentificate(email, password_digest)
		user = find_by_email(email)
		if user && user.password_digest == password_digest
			user			
		end
	end

end

D06/ex00/LifeProTips/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

D06/ex00/LifeProTips/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  require 'open-uri'

  def new() end

  def create
	user = User.authentificate(params[:email], params[:password_digest])
	if user
	  redirect_to root_url, notice: "Logged in as #{user.name}!"
	else
	  flash.now[:alert] = "Invalid Password!"
	  render :new
	end
  end

  def animal_name
  if cookies[:name].nil?
    url = "https://www.randomlists.com/random-animals"
	doc = Nokogiri::HTML(open(url))
    animal = doc.css('li').first.css('span').text
    cookies[:name] = {value: animal, expires: 1.minute.from_now}
   end
   end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end

  def home
    animal_name
  end
end

D06/ex00/LifeProTips/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	
	def create
		@user = User.new(user_params)
		params[:user][:name] = cookies[:name] unless params[:user][:name].present?
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Logged in as #{@user.name}!"
		else
			render :new
		end
	end

	def user_params
		params.require(:user).permit(:name, :email, :password_digest)
	end

end

D06/ex00/LifeProTips/app/helpers/sessions_helper.rb
module SessionsHelper
end

D06/ex00/LifeProTips/app/helpers/users_helper.rb
module UsersHelper
end

D06/ex00/LifeProTips/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LifeProTips</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>