D04/ex01/CheatSeet/config/routes.rb
Rails.application.routes.draw do

  root 'pages#convention'
  get '/editor' => 'pages#editor'
  get '/convention' => 'pages#convention'
  get '/ruby' => 'pages#ruby'
  get '/console' => 'pages#console'
  get '/numbers' => 'pages#numbers'
  get '/strings' => 'pages#strings'
  get '/arrays' => 'pages#arrays'
  get '/hashes' => 'pages#hashes'
  get '/rails_app' => 'pages#rails_app'
  get '/rails_commands' => 'pages#rails_commands'
  get '/embedded_ruby' => 'pages#embedded_ruby'
  get '/help' => 'pages#help'
  get '/quick_search' => 'pages#quick_search'

end

D04/ex01/CheatSeet/app/controllers/application_controller.rb
#commenter pour ne rien dire
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

D04/ex01/CheatSeet/app/controllers/pages_controller.rb
#commenter pour ne rien dire
class PagesController < ApplicationController
#commenter pour ne rien dire
	def editor
		@title = "editor"
	end

	def convention
		@title = "convention"
	end

	def ruby
		@title = "ruby"
	end

	def console
		@title = "console"
	end

	def numbers
		@title = "numbers"
	end

	def strings
		@title = "strings"
	end

	def arrays
		@title = "arrays"
	end

	def hashes
		@title = "hashes"
	end

	def rails_app
		@title = "rails_app"
	end

	def rails_commands
		@title = "rails_commands"
	end

	def embedded_ruby
		@title = "embedded_ruby"
	end

	def help
		@title = "help"
	end
	
	def quick_search
		@title = "quick_search"
	end

end

D04/ex01/CheatSeet/app/helpers/application_helper.rb
#commenter pour ne rien dire
module ApplicationHelper
#commenter pour ne rien dire
end

D04/ex01/CheatSeet/app/helpers/pages_helper.rb
#commenter pour ne rien dire
module PagesHelper
#commenter pour ne rien dire
end

D04/ex01/CheatSeet/app/views/pages/_navbar.html.erb
<div class="container">
  <nav>
    <div class="navbar navbar-fixed-top navbar-default"><div class="navbar-header"><%= link_to "Rails Beginner Cheat Sheet", convention_path, class: "navbar-brand cheat-sheet-brand" %></div>


      <ul class="nav navbar-nav">
        <li><%= link_to "Console", console_path %></li>
        <li class="dropdown">
          <a href="./#ruby" class="dropdown-toggle"><b class="caret"></b> Ruby</a>
          <ul class="dropdown-menu">
            <li><%= link_to "General Concepts", ruby_path %></li>
            <li><%= link_to "Numbers", numbers_path %></li>
            <li><%= link_to "Strings", strings_path %></li>
            <li><%= link_to "Arrays", arrays_path %></li>
            <li><%= link_to "Hashes", hashes_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="./#rails"><b class="caret"></b> Rails</a>
          <ul class="dropdown-menu">
            <li><%= link_to "Folder Structure", rails_app_path %></li>
            <li><%= link_to "Commands", rails_commands_path %></li>
            <li><%= link_to "ERB: Embedded Ruby", embedded_ruby_path %></li>
          </ul>
        </li>
          <li><%= link_to "Quick search", quick_search_path %></li>
        <li><%= link_to "Editor Tips", editor_path %></li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
      <ul class="nav pull-right navbar-nav">
        <li><a href="#">Resources</a></li>
        <li><a href="#">About</a></li>
      </ul>
    </div>
  </nav>
</div>

D04/ex01/CheatSeet/app/views/pages/arrays.html.erb
<h2 id="ruby-arrays">Arrays</h2>

<p>
  An array is an ordered collection of items which is indexed by numbers.
  So an array contains multiple objects that are mostly related to each
  other. So what could you do? You could store a collection of the names
  of your favorite fruits and name it <em>fruits</em>.
</p>

<p>
  This is just a small selection of things an Array can do. For more
  information have a look at the
  <a href=http://ruby-doc.org/core-2.0/Array.html>ruby-doc for Array</a>.
</p>

<table class="table table-striped">
  <tr>
    <th class="concept">Concept</th>
    <th class="usage">Usage</th>
    <th class="example">Examples</th>
    <th class="description">Description</th>
  </tr>
  <tr>
    <td>Create</td>
    <td>
      <code><strong>[</strong><em>contents</em><strong>]</strong></code>
    </td>
    <td>
      <p><code><strong>[]</strong></code></p>

      <p><code>
        <strong>[</strong><em>"Rails", "fun", 5</em><strong>]</strong>
      </code></p>
    </td>
    <td>Creates an Array, empty or with the specified contents.</td>
  </tr>
  <tr>
    <td>Number of elements</td>
    <td>
      <code>array<strong>.size</strong></code>
    </td>
    <td>
      <p><code>[]<strong>.size</strong> # => 0</code></p>

      <p><code>[1, 2, 3]<strong>.size</strong> # => 3</code></p>

      <p><code>["foo", "bar"]<strong>.size</strong> # => 2</code></p>
    </td>
    <td>Returns the number of elements in an Array.</td>
  </tr>
  <tr>
    <td>Access</td>
    <td>
      <code>
        array<strong>[</strong><em>position</em><strong>]</strong>
      </code>
    </td>
    <td>
<pre><code>array = ["hi", "foo", "bar"]
array<strong>[</strong><em>0</em><strong>]</strong> # => "hi"
array<strong>[</strong><em>2</em><strong>]</strong> # => "bar"</code></pre>
    </td>
    <td>As an Array is a collection of different elements, you often want
      to access a single element of the Array.
      Arrays are indexed by numbers so you can use a number
      to access an individual element. Be aware that the
      numbering actually starts with "0" so the first element
      actually is the 0th. And the last element of a three element
      array is element number 2.
    </td>
  </tr>
  <tr>
    <td>Adding an element</td>
    <td>
      <code>array <strong>&lt;&lt;</strong> <em>element</em></code>
    </td>
    <td>
<pre><code>array = [1, 2, 3]
array <strong>&lt;&lt;</strong> <em>4</em>
array # => [1, 2, 3, 4]
</code></pre>
    </td>
    <td>
      Adds the element to the end of the array,
      increasing the size of the array by one.
    </td>
  </tr>
  <tr>
    <td>Assigning</td>
    <td>
      <code>array<strong>[</strong><em>number</em><strong>] =
      </strong> <em>value</em></code>
    </td>
    <td>
<pre><code>array = ["hi", "foo", "bar"]
array<strong>[</strong><em>2</em><strong>] =</strong> <em>"new"</em>
array # => ["hi", "foo", "new"]</code></pre>
    </td>
    <td>Assigning new Array Values works a lot like accessing
      them; use an equals sign to set a new value. Voila!
      You changed an element of the array! Weehuuuuu!
    </td>
  </tr>
  <tr>
    <td>Delete at index</td>
    <td><code>
      array<strong>.delete_at</strong><em>(i)</em>
    </code></td>
    <td>
<pre><code>array = [0, 14, 55, 79]
array<strong>.delete_at</strong><em>(2)</em>
array # => [0, 14, 79]
</code></pre>
    </td>
    <td>
      Deletes the element of the array at the specified index. Remember
      that indexing starts at 0. If you specify an index larger than the
      number of elements in the array, nothing will happen.
    </td>
  </tr>
  <tr>
    <td>Iterating</td>
    <td>
      <code>array<strong>.each</strong> <em>do |e| .. end</em></code>
    </td>
    <td>
      <p><code>
        persons<strong>.each</strong> <em>do |p| puts p.name end</em>
      </code></p>

      <p><code>
        numbers<strong>.each</strong> <em>do |n| n = n * 2 end</em>
      </code></p>
    </td>
    <td>
      <p>
        "Iterating" means doing something for <em>each</em> element
        of the array. Code placed between <em>do</em> and <em>end</em>
        determines what is done to each element in the array.
      </p>

      <p>
        The first example prints the name of every person in the array to
        the console. The second example simply doubles every number of a
        given array.
      </p>
    </td>
  </tr>
</table>

D04/ex01/CheatSeet/app/views/pages/console.html.erb
<h1 id="console">Console Basics</h1>

<p>
  The console (also called <em>command line, command prompt or
  terminal</em>) is just another way of interacting with your computer.
  So you can basically do anything with it that you could also do with
  your graphical desktop user interface. This sections contains a couple
  of examples.
</p>

<p>
  For the different operating systems <strong>starting the console</strong>
  differs.
</p>

<ul>
  <li><strong>Windows:</strong> Open the start menu and search for
    command prompt. Alternatively choose <em>execute</em> and enter
    <em>cmd</em>.</li>
  <li><strong>Mac:</strong> Open Spotlight, type <em>terminal</em>, and
    start that program.
  </li>
  <li><strong>Linux:</strong> The terminal should be one of the main
    options once you open the main menu of your distribution. Otherwise
    search for <em>terminal</em> if your distribution has such an option
    or look under Accessories.
  </li>
</ul>

<table class="table table-striped">
  <tr>
    <th class="concept">Concept</th>
    <th class="usage">Usage</th>
    <th class="example">Examples</th>
    <th class="description">Description</th>
  </tr>
  <tr>
    <td>Change directory</td>
    <td>
      <code><strong>cd</strong> <em>directory</em></code>
    </td>
    <td>
      <p><code>cd my_app</code></p>

      <p><code>cd my_app/app/controllers</code></p>
    </td>
    <td>Changes the directory to the specified directory on the
      console.
    </td>
  </tr>
  <tr>
    <td>List contents directory</td>
    <td>
      <p><code><strong>ls</strong> <em>directory</em></code></p>

      <p><code>Windows: <strong>dir</strong> <em>directory</em></code>
      </p>
    </td>
    <td>
      <p><code><strong>ls</strong></code></p>

      <p><code><strong>ls</strong> <em>my_app</em></code></p>
    </td>
    <td>Shows all contents (files and folders) of the directory.
      If no directory is specified shows the contents of the
      current directory.
    </td>
  </tr>
  <tr>
    <td>Directory you are currently in</td>
    <td><code><strong>pwd</strong></code></td>
    <td><code><strong>pwd</strong></code></td>
    <td>Shows the full path of the directory you are currently
      in. E.g. /home/tobi/railsgirls
      <br />
      A note on filenames: if a file or directory name starts with a slash / as in the output of pwd above, it is an absolute filename specifying the complete filename starting at the root of the current file system (e.g. hard disk). If the slash (/) is omitted, the file name is relative to the current working directory.
    </td>
  </tr>
  <tr>
    <td>Create a new directory</td>
    <td><code><strong>mkdir</strong> <em>name</em></code></td>
    <td>
      <p><code><strong>mkdir</strong> <em>rails</em></code></p>
      <p><code><strong>mkdir</strong> <em>fun</em></code></p>
    </td>
    <td>
      Creates a directory with the given name in the folder you are currently
      in.
    </td>
  </tr>
  <tr>
    <td>Delete a file</td>
    <td>
      <p><code><strong>rm</strong> <em>file</em></code></p>

      <p><code>Windows: <strong>del</strong> <em>file</em></code>
    </td>
    <td>
      <p><code><strong>rm</strong> <em>foo</em></code></p>
      <p><code><strong>rm</strong> <em>index.html</em></code></p>
      <p><code><strong>rm</strong> <em>pictures/old_picture.jpg</em></code></p>
    </td>
    <td>
      <p>Deletes the specified file. Be <strong>extra cautious</strong> with this
      as it would be too bad to delete something you still need :-(</p>
      <p>
        You can simply specify the name of a file of the directory you are
        currently in. However you can also specify a path, this is shown in the
        third example. There we delete the <em>old_picture.jpg</em> file from
        the <em>pictures</em> folder.
      </p>
    </td>
  </tr>
  <tr>
    <td>Delete a directory</td>
    <td>
      <p><code><strong>rm -r</strong> <em>folder</em></code></p>

      <p><code>Windows: <strong>rd</strong> <em>folder</em></code>
    </td>
    <td>
      <p><code><strong>rm -r</strong> <em>stuff_i_dont_need</em></code></p>
      <p><code><strong>rm -r</strong> <em>stuff_i_dont_need/</em></code></p>
      <p><code><strong>rm -r</strong> <em>old_application</em></code></p>
    </td>
    <td>
      <p>Deletes the specified folder <strong>and all of its contents</strong>.
        So please be <strong>super cautious</strong> with this! Make sure that
        you do not need any of the contents of this folder any more.
      </p>
      <p>
        So why would you want to delete a whole folder? Well maybe it was an old
        application that you do not need anymore :-)
      </p>
    </td>
  </tr>
  <tr>
    <td>Starting a program</td>
    <td><code><strong>program</strong> <em>arguments</em></code></td>
    <td>
      <p><code><strong>firefox</strong></code></p>

      <p><code>
        <strong>firefox</strong> <em>railsgirlsberlin.de</em></code>
      </p>

      <p><code><strong>irb</strong></code></p>
    </td>
    <td>Starts the program with the given name and arbitrary arguments
      if the program takes arguments. Firefox is just one example. Starting
      Firefox without arguments just opens up Firefox. If you give it an
      argument it opens the specified URL.
      When you type in <code>irb</code> this starts <em>interactive ruby</em>.
    </td>
  </tr>
  <tr>
    <td>Abort the program</td>
    <td>Press <strong>Ctrl + C</strong></td>
    <td>-</td>
    <td>This will abort the program currently running in the terminal.
      For instance this is used to shut down the Rails server.
      You can also abort many other related tasks with it, including:
      bundle install, rake db:migrate, git pull and many more!
    </td>
  </tr>
</table>

D04/ex01/CheatSeet/app/views/pages/convention.html.erb
<div id="content-wrapper">
  <div class="container ">
    <section id="main-content">
      <h1>Cheat Sheet Conventions</h1>

<p>
  <strong>Bold</strong> words are what is really important e.g.
  the command and concept shown in the usage category. In the code usage and
  example columns these highlight the main part of the concept, like this:
  <code>general_stuff<strong>.concept</strong></code>.
  In the same columns <code><em>italic_words</em></code> mark the
  arguments/parameters of a command/method.
</p>

<p>
  However <em>italic words</em> in the descriptions or general text denote
  more general concepts or concepts explained elsewhere in this cheat
  sheet or in general.
</p>


<h1 id="ruby">Ruby Basics</h1>

<p>
  Ruby is the programming language Ruby on Rails is written in. So most
  of the time you will be writing Ruby code. Therefore it is good to
  grasp the basics of Ruby. If you just want to play with Ruby, type
  <strong>irb</strong> into your console to start interactive ruby. There
  you can easily experiment with Ruby. To leave irb, type
  <strong>exit</strong>.
</p>

<p>
  This is just a very small selection of concepts. This is especially
  true later on when we talk about what Arrays, Strings etc. can do.
  For more complete information have a look at
  <a href="http://ruby-doc.org/">ruby-doc</a> or search with your favorite
  search engine!
</p>








<footer>
  <div class="footer-constrain">
    <p>created by <a href="http://pragtob.info">Tobias Pfeiffer</a></p>
    <ul class="footer-links">
      <li><a href="#">About</a></li>
      <li class="text-muted">·</li>
      <li><a href="#">Resources</a></li>
      <li class="text-muted">·</li>
      <li><a href="http://pragtob.wordpress.com/">Blog</a></li>
    </ul>
  </div>
</footer>

D04/ex01/CheatSeet/app/views/pages/editor.html.erb
<h1 id="editor">Editor tips</h1>

<p>
  When you write code you will be using a text editor. Of course each text
  editor is different and configurable. Here are just some functions and
  their most general short cuts. All of them work in
  <a href="https://sublimetext.com/2">Sublime Text 2</a>. Your editor may
  differ!
</p>

<p>
  The shortcuts listed here are for Linux/Windows. On a Mac you will have
  to replace <em>Ctrl</em> with <em>Cmd</em>.
</p>

<table class="table table-striped">
  <tr>
    <th>Function</th>
    <th class="shortcut">Shortcut</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>Save file</td>
    <td><strong>Ctrl + S</strong></td>
    <td>
      Saves the currently open file. If it was a new file you may also be
      asked where to save it.
    </td>
  </tr>
  <tr>
    <td>Undo</td>
    <td><strong>Ctrl + Z</strong></td>
    <td>
      Undo the last change you made to the current file. Can be applied
      multiple times in succession to undo multiple changes.
    </td>
  </tr>
  <tr>
    <td>Redo</td>
    <td><p><strong>Ctrl + Y</strong></p>

      <p><em>or Ctrl + Shift + Z</em></p></td>
    <td>
      Redo what you just undid with <em>undo</em>, can also be done
      multiple times.
    </td>
  </tr>
  <tr>
    <td>Find in File</td>
    <td><strong>Ctrl + F</strong></td>
    <td>
      Search for a character sequence within the currently open file.
      Hit <em>Enter</em> to progress to the next match.
    </td>
  </tr>
  <tr>
    <td>Find in all Files</td>
    <td><strong>Ctrl + Shift + F</strong></td>
    <td>Search for a character sequence in all files of the project.</td>
  </tr>
  <tr>
    <td>Replace</td>
    <td>
      <p><strong>Ctrl + H</strong></p>

      <p><em>or Ctrl + R</em></p>
    </td>
    <td>
      Replace occurrences of the supplied character sequence with the
      other supplied character sequence. Useful when renaming something.
    </td>
  </tr>
  <tr>
    <td>Copy</td>
    <td><strong>Ctrl + C</strong></td>
    <td>
      Copy the currently highlighted text into the clipboard.
    </td>
  </tr>
  <tr>
    <td>Cut</td>
    <td><strong>Ctrl + X</strong></td>
    <td>Copy the highlighted text into the clipboard but delete it.</td>
  </tr>
  <tr>
    <td>Paste</td>
    <td><strong>Ctrl + V</strong></td>
    <td>
      Insert whatever currently is in the clipboard (through
      <em>Copy</em> or <em>Cut</em>) at the current caret position.
      Can insert multiple times.
    </td>
  </tr>
  <tr>
    <td>New File</td>
    <td><strong>Ctrl + N</strong></td>
    <td>Create a new empty file.</td>
  </tr>
  <tr>
    <td>Search and open file</td>
    <td><strong>Ctrl + P</strong></td>
    <td>
      Search for a file giving part of its name (<em>fuzzy search</em>).
      Pressing <em>enter</em> will open the selected file.
    </td>
  </tr>
  <tr>
    <td>Comment</td>
    <td><strong>Ctrl + /</strong></td>
    <td>
      Marks the selected text as a comment, which means that it will
      be ignored. Useful when you want to see how something behaves or looks
      without a specific section of code being run.
    </td>
  </tr>
</table>

D04/ex01/CheatSeet/app/views/pages/embedded_ruby.html.erb
<h2 id="rails-erb">ERB: Embedded Ruby</h2>
<p>
  In your views (that is, under <code>app/views</code> in your Rails app) you
  will find <code>.html.<strong>erb</strong></code> files. <strong>ERB</strong>
  stands for <strong>E</strong>mbedded <strong>R</strong>u<strong>B</strong>y.
  This just means that Rails processes some special tags in those files and
  produces HTML output to send back to the user.
</p>
<p>
  There are two ERB tags that you need to remember:
  <code>&lt;%= <i>ruby_code</i> %&gt;</code> and
  <code>&lt;% <i>ruby_code</i> %&gt;</code>. Notice that the difference is the
  <strong>=</strong> in the first tag.
</p>

<table class="table table-striped">
  <tr>
    <th class="usage">Tag</th>
    <th class="erb-example">Examples</th>
    <th class="description">Description</th>
  </tr>
  <tr>
    <td><code>&lt;%<strong>=</strong> %&gt;</code></td>
    <td><code><strong>&lt;%= @product.price %&gt;</strong></code></td>
    <td>
      It runs the Ruby code and inserts the result to the HTML at that position.
      You can put <em>any kind of Ruby code</em> between <code>&lt;%=</code> and
      <code>%&gt;</code>, for instance, <code>&lt;%= 9 * 3 %&gt;</code> will translate to
      <strong>27</strong> in the page that the user is viewing. However,
      typically this tag is used to display some data from a model, such as the
      price of a product, as shown in the example here.
    </td>
  </tr>
  <tr>
    <td><code>&lt;% %&gt;</code></td>
    <td>
<pre><code><strong>&lt;% if user.admin? %&gt;</strong>
  &lt;p&gt;Hello Admin!&lt;/p&gt;
&lt;% end %&gt;</code></pre></td>
    <td>
      The Ruby code between the delimiters <code>&lt;%</code> and <code>%&gt;</code>
      is run but the result will <strong>not</strong> be inserted at this point
      in the HTML. Therefore these tags are most commonly used for control flow
      structures such as an if statement in the example, or loops.
    </td>
  </tr>
</table>

D04/ex01/CheatSeet/app/views/pages/hashes.html.erb
<h2 id="ruby-hashes">Hashes</h2>

<p>
  Hashes associate a <em>key</em>  to some <em>value</em>. You may then retrieve the value based upon its key.
  This construct is called a <em>dictionary</em> in other languages, which is appropriate
  because you use the key to "look up" a value, as you would look up a definition for
  a word in a dictionary. Each key must be unique for a given hash but values can be repeated.
</p>

<p>
  Hashes can map from anything to anything! You can map from Strings to
  Numbers, Strings to Strings, Numbers to Booleans... and you can mix
  all of those! Although it is common that at least all the keys are of
  the same class. <em>Symbols</em> are especially common as keys. Symbols
  look like this: <code>:symbol</code>. A symbol is a colon followed by some
  characters. You can think of them as special strings that stand for
  (symbolize) something! We often use symbols because
  Ruby runs faster when we use symbols instead of strings.
</p>

<p>Learn more about hashes at
  <a href="http://www.ruby-doc.org/core-2.0/Hash.html">ruby-doc</a>.
</p>

<table class="table table-striped">
  <tr>
    <th class="concept">Concept</th>
    <th class="usage">Usage</th>
    <th class="hash-example">Examples</th>
    <th class="description">Description</th>
  </tr>
  <tr>
    <td>Creating</td>
    <td><code>
      <strong>{</strong>key <strong>=></strong> value<strong>}</strong>
    </code></td>
    <td>
      <p><code>
        <strong>{</strong>:hobby <strong>=></strong>
        "programming"<strong>}</strong>
      </code></p>
<pre><code><strong>{</strong>42 <strong>=></strong> "answer", "score" <strong>=></strong> 100,
 :name <strong>=></strong> "Tobi"<strong>}</strong>
</code></pre>
    </td>
    <td>
      You create a hash by surrounding the key-value pairs with curly
      braces. The arrow always goes from the <em>key</em> to the
      <em>value</em> depicting the meaning: <em>"This key points to this
      value."</em>. Key-value pairs are then separated by commas.
    </td>
  </tr>
  <tr>
    <td>Accessing</td>
    <td><code>hash<strong>[</strong>key<strong>]</strong></code></td>
    <td>
<pre><code>hash = {:key => "value"}
hash<strong>[</strong>:key<strong>]</strong> # => "value"
hash<strong>[</strong>foo<strong>]</strong> # => nil
</code></pre>
    </td>
    <td>
      Accessing an entry in a hash looks a lot like accessing it in
      an <em>array</em>. However with a hash the key can be anything, not
      just numbers. If you try to access a key that does not exist, the
      value <code>nil</code> is returned, which is Ruby's way of saying
      "nothing", because if it doesn't recognize the key it can't return
      a value for it.
    </td>
  </tr>
  <tr>
    <td>Assigning</td>
    <td>
      <code>hash<strong>[</strong>key<strong>] =</strong> value</code>
    </td>
    <td>
<pre><code>hash = {:a => "b"}
hash<strong>[</strong>:key<strong>] =</strong> "value"
hash # => {:a=>"b", :key=>"value"}
</code></pre>
    </td>
    <td>
      Assigning values to a hash is similar to assigning values to an
      array. With a hash, the key can
      be a number or it can be a symbol, string,
      number... or anything, really!
    </td>
  </tr>
  <tr>
    <td>Deleting</td>
    <td><code>hash<strong>.delete</strong><em>(key)</em></code></td>
    <td>
<pre><code>hash = {:a => "b", :b => 10}
hash<strong>.delete</strong><em>(:a)</em>
hash # => {:b=>10}
</code></pre>
    </td>
    <td>
      You can delete a specified key from the hash, so that the key and its
      value can not be accessed.
    </td>
  </tr>
</table>

D04/ex01/CheatSeet/app/views/pages/help.html.erb
<h1 id="help">Help: What to do when things go wrong?</h1>

<p>
  Things go wrong all the time. Don't worry, this happens to everyone.
  So keep calm. When you encounter an error, just google the error message.
  For best results, add the keywords "rails" or "ruby". Results from
  <a href="http://stackoverflow.com/questions/tagged/ruby-on-rails?sort=newest">stackoverflow.com</a>
  are often really helpful. Look for those! The most experienced developers do this frequently ;-).
  </p>

<p>
  Here are common mistakes with a little checklist:
</p>

<ul>
  <li>Have you run <em>rake db:migrate</em> to apply the newest database
    migrations?
  </li>
  <li>Have you really saved the file you just changed? Unsaved files are
    often marked in the editor via an asterisk or a point next to their
    name.
  </li>
  <li>If you just added a gem to the Gemfile, have you run <em>bundle
    install</em> to install it?
  </li>
  <li>If you just installed a gem, have you restarted the server?</li>
</ul>

<p>
  Do you need more beginner friendly in depth information about Ruby on Rails?
  We have started to gather free tutorials and learning material on a
  <strong><a href="resources.html">resources</a></strong> page! Please give
  feedback about your
  favorite tutorials and lessons!
</p>

    </section>
  </div>
</div>

D04/ex01/CheatSeet/app/views/pages/numbers.html.erb
<h2 id="ruby-numbers">Numbers</h2>

<p>
  Numbers are what you would expect them to be, normal
  numbers that you use to perform basic math operations.
</p>

<p>
  More information about numbers can be found in the
  <a href="http://ruby-doc.org/core-2.0/Numeric.html">ruby-doc of Numeric</a>.
</p>

<table class="table table-striped">
  <tr>
    <th class="concept">Concept</th>
    <th class="usage">Usage</th>
    <th class="example">Examples</th>
    <th class="description">Description</th>
  </tr>
  <tr>
    <td>normal Number</td>
    <td><code><strong>number_of_your_choice</strong></code></td>
    <td>
      <p><code><strong>0</strong></code></p>

      <p><code><strong>-11</strong></code></p>

      <p><code><strong>42</strong></code></p>
    </td>
    <td>
      Numbers are natural for Ruby, you just have to enter them!
    </td>
  </tr>
  <tr>
    <td>Decimals</td>
    <td><code><strong>main.decimal</strong></code></td>
    <td>
      <p><code><strong>3.2</strong></code></p>

      <p><code><strong>-5.0</strong></code></p>
    </td>
    <td>
      You can achieve decimal numbers in Ruby simply by adding a point.
    </td>
  </tr>
  <tr>
    <td>Basic Math</td>
    <td>
      <code>n <strong>operator</strong> <em>m</em></code>
    </td>
    <td>
      <p><code>2 <strong>+</strong> <em>3</em> # => 5</code></p>

      <p><code>5 <strong>-</strong> <em>7</em> # => -2</code></p>

      <p><code>8 <strong>*</strong> <em>7</em> # => 56</code></p>

      <p><code>84 <strong>/</strong> <em>4</em> # => 21</code></p>
    </td>
    <td>
      In Ruby you can easily use basic math operations.
      In that sense you may use Ruby as a super-powered calculator.
    </td>
  </tr>
  <tr>
    <td>Comparison</td>
    <td>
      <code>n <strong>operator</strong> <em>m</em></code>
    </td>
    <td>
      <p><code>12 <strong>&gt;</strong> <em>3</em> # => true</code></p>

      <p><code>12 <strong>&lt;</strong> <em>3</em> # => false</code></p>

      <p><code>7 <strong>&gt;=</strong> <em>7</em> # => true</code></p>
    </td>
    <td>
      <p>Numbers may be compared to determine if a number is bigger or smaller
        than another number. When you have the age of a person saved in the
        <code>age</code> variable you can see if that person is considered
        an adult in Germany:</p>

      <p><code>age >= 18 # true or false</code></p>
    </td>
  </tr>
</table>